GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQW5keSIsImlhdCI6MTYwOTA2MzkyOX0.R3XpOwqUNrBQQD02AIUVhDFtCVLRJ_D2mbL9EGpPsvo

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Andy"
}